config/routes.rb
WakeupHeroku::Application.routes.draw do
  scope constraints: ->(request) { request.session['current_user_id'].present? } do
    resources :heroku_applications do
      resource :toggle_activation, only: [:create], controller: 'heroku_applications/toggle_activation'
    end
    resource :syncing, only: [:create], controller: 'syncing'

    root 'heroku_applications#index', as: 'signed_in_root'
  end

  get '/auth/:provider/callback' => 'sessions#create'

  resources :sessions, only: [:new, :destroy]

  root 'welcome#index'
end

app/models/application.rb
class Application
  include Mongoid::Document

  embedded_in :user

  field :activated, type: Boolean, default: false
  field :heroku_id, type: String
  field :last_ping, type: DateTime
  field :name,      type: String
  field :status,    type: String
  field :url,       type: String

  validates :status, allow_nil: true, inclusion: { in: ['up', 'down'] }
end

app/models/user.rb
class User
  include Mongoid::Document

  embeds_many :applications

  field :api_token,    type: String
  field :email,        type: String
  field :heroku_id,    type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  analytical use_session_store: true
  protect_from_forgery with: :exception

  def current_user
    if (user_id = session['current_user_id'])
      @current_user ||= User.where(id: user_id).first
    end
  end
  helper_method :current_user
end

app/controllers/heroku_applications/toggle_activation_controller.rb
module HerokuApplications
  class ToggleActivationController < SignedInController
    def create
      application           = current_user.applications.where(heroku_id: params[:heroku_application_id]).first
      application.activated = !application.activated

      if application.save
        analytic_event = application.activated ? 'Activate' : 'Deactivate'
        analytical.event("#{analytic_event} application", id: current_user.heroku_id, application_id: application.heroku_id)
      end

      redirect_to signed_in_root_path
    end
  end
end

app/controllers/heroku_applications_controller.rb
class HerokuApplicationsController < SignedInController
  expose(:applications) { current_user.applications }
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to '/auth/heroku'
  end

  def create
    api_key = request.env['omniauth.auth']['credentials']['token']
    user    = create_or_update_user(api_key)

    session['current_user_id'] = user.id

    redirect_to signed_in_root_path
  end

  def destroy
    analytical.event('Signout', id: current_user.heroku_id)

    session['current_user_id'] = nil if params[:id].to_s == session['current_user_id'].to_s
    redirect_to root_path
  end

private

  def create_or_update_user(api_key)
    heroku_api     = Heroku::API.new(api_key: api_key)
    heroku_user    = heroku_api.get_user.body

    user           = User.find_or_initialize_by(heroku_id: heroku_user['id'])
    user.api_token = api_key
    user.email     = heroku_user['email']

    analytic_event = user.new_record? ? 'Signup' : 'Signin'
    analytical.event(analytic_event, id: user.heroku_id)

    create_heroku_applications(user, heroku_api) unless user.applications.present?

    user.save

    user
  end

  def create_heroku_applications(user, heroku_api)
    applications = heroku_api.get_apps.body
    applications.each do |application|
      application = Application.new(heroku_id: application['id'], name: application['name'], url: application['web_url'])
      analytical.event('Add application', id: user.heroku_id, application_id: application.heroku_id, application_name: application.name)

      user.applications << application
    end
  end
end

app/controllers/signed_in_controller.rb
class SignedInController < ApplicationController
  before_filter :signed_in

private

  def signed_in
    redirect_to root_path unless current_user
  end
end

app/controllers/syncing_controller.rb
class SyncingController < SignedInController
  def create
    heroku_api          = Heroku::API.new(api_key: current_user.api_token)
    heroku_applications = heroku_api.get_apps.body

    add_or_update_exising_applications(heroku_applications)
    remove_deleted_applications(heroku_applications)

    analytical.event('Sync applications', id: current_user.heroku_id)

    redirect_to signed_in_root_path
  end

private

  def add_or_update_exising_applications(heroku_applications)
    heroku_applications.each do |heroku_application|
      application      = current_user.applications.find_or_create_by(heroku_id: heroku_application['id'])
      application.name = heroku_application['name']
      application.url  = heroku_application['web_url']

      analytical.event('Add application', id: current_user.heroku_id, application_id: application.heroku_id, application_name: application.name)

      application.save
    end
  end

  def remove_deleted_applications(heroku_applications)
    heroku_application_ids = heroku_applications.map { |heroku_application| heroku_application['id'] }
    removable_applications = current_user.applications.reject { |application| heroku_application_ids.include?(application.heroku_id.to_i) }

    removable_applications.each do |application|
      analytical.event('Remove application', id: current_user.heroku_id, application_id: application.heroku_id, application_name: application.name)

      application.destroy
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/general/_menu.html.slim
nav class="top-bar"
  ul class="title-area"
    li class="name"
      h1
        = link_to('Wake up Heroku', root_path)
    li class="toggle-topbar menu-icon"
      = link_to('Menu', '#')
  ul class="right"
    - if current_user
      li class="has-form"
        li = link_to('Sign out', session_path(current_user), class: 'button', method: :delete)
    - else
      = link_to('Sign in', new_session_path, class: 'button')

app/views/heroku_applications/index.html.slim
div class="row"
  div class="large-12 colomns"
    = button_to('Sync Heroku applications', syncing_path, class: 'small right button primary-dark', method: :post)

div class="row"
  div class="large-12 colomns"
    table
      thead
        tr
          th Name
          th Activated
          th Last Ping
          th status
      tbdody
        - applications.each do |application|
          tr
            td= application.name
            td
              = link_to(heroku_application_toggle_activation_path(application.heroku_id), method: 'post') do
                div class="switch small round"
                  = radio_button_tag("switch-#{application.id}", '', !application.activated, id: "activate_#{application.id}")
                  label for="deactivate_#{application.id}"
                    |Off

                  = radio_button_tag("switch-#{application.id}", '', application.activated, id: "activate_#{application.id}")
                  label for="activate_#{application.id}"
                    |On

                  span
            td
              - if application.last_ping
                = l(application.last_ping, format: :long)
              - else
                | Not yet pinged
            td
              span class="status-#{application.status.presence || 'no-status'}"

app/views/layouts/application.html.slim
doctype html
html
  head
    == analytical.head_prepend_javascript
    title Wakeup Heroku
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    - analytical.identify current_user.heroku_id, email: current_user.email if current_user
    == analytical.head_append_javascript
body
  == analytical.body_prepend_javascript
  = render 'general/menu'
  div class="row"
    div class="large-12 colomns"
      = yield
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  == analytical.body_append_javascript

app/views/welcome/index.html.slim
div class="large-12 columns"
  h1
    | 3 steps to have an always up Heroku app
div class="large-4 columns m-steps"
  = image_tag('sign_in.png', height: '50%', width: '50%')
  div class="large-12 columns m-steps--description"
    | 1. Sign in with your Heroku account

div class="large-4 columns m-steps"
  = image_tag('activate.png', height: '50%', width: '50%')
  div class="large-12 columns m-steps--description"
    | 2. Activate your application

div class="large-4 columns m-steps"
  = image_tag('enjoy.png', height: '50%', width: '50%')
  div class="large-12 columns m-steps--description"
    | 3. Your app never sleep again

div class="large-12 columns m-signin"
  = link_to('Sign in with Heroku', new_session_path, class: 'button highlight-dark')